theme:          minima
source:         source
plugins:
  - jekyll-redirect-from
#  - jekyll-data
#  - jekyll-gzip
#  - jekyll-liquify

logo:           assets/images/logos/emm_logo.png

exclude:        [node_modules]
sass:
  style:        compressed
  sass_dir:     _sass

root_url:       https://entity-metadata-management.io

navbar_menu:
  - label: 'API'
    link: '{{ site.root_url }}/api'
  - label: 'Demos'
    link: '{{ site.root_url }}/demos'

footer_menu:
  - label: 'API'
    link: '{{ site.root_url }}/api'
  - label: 'Demos'
    link: '{{ site.root_url }}/demos'
