# BUILD SETTINGS

url:            ''
baseurl:        ''
permalink:      pretty
theme:          emm-theme
source:         source
google_analytics:   # UA-XXXXXXX-XX

markdown:       kramdown
exclude:        [node_modules]
sass:
  style:        compressed
  sass_dir:     _sass

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from
  - jekyll-liquify

# URLS
root_url:       https://entity-metadata-management.io
api_url:        https://entity-metadata-management.io/api
guides_url:     # https://entity-metadata-management.io/guides # perhaps use for links to example Activity Streams

# THEME VARS
emm-theme:
  logo:       assets/images/logos/emm_logo.png
  acronym:    EEM
  title:      Entity Metadata Management
  tagline:    "EMM is a set of open standards for describing methods for managing the lifecyle of entity metadata."
  email:      emm-discuss@googlegroups.com
  block-start: "<div class='container-block is-max-widescreen'><div class='container' markdown='1'>"
  block-center-start: '<div class="container-block is-max-widescreen"><div class="container has-text-centered" markdown="1">'
  block-end: '</div></div>'
  navbar_menu:
    - label: 'API'
      link: '{{ site.root_url }}/api'
    - label: 'Demos'
      link: '{{ site.root_url }}/demos'
  footer_menu:
    - heading: About
      sub:
        - label: 'Change Document API'
          link:  '{{ site.root_url }}/api/'
        - label: 'Demos'
          link:  '{{ site.root_url }}/demos/'
        - label: 'License & Disclaimer'
          link:  '{{ site.root_url }}/license'
        - label: 'Privacy policy'
          link:  '{{ site.root_url }}/privacy'
