theme:          minima
plugins:
  - jekyll-redirect-from

logo:           assets/images/logos/emm_logo.png

exclude:        [node_modules]
sass:
  style:        compressed
  sass_dir:     _sass

# Lastest stable version of the specification
major: 1
minor: 0
patch: 0
